Repository learnhubmk/app, pull requests merged in 2024-03, with the labels that each got.

#16 Readme file updated
  README.md
Labels: documentation

#17 ESLint, babel & husky init setup
  .babelrc
  .eslintrc.json
  .husky/pre-commit
  .lintstagedrc
  package-lock.json
  package.json
Labels: enhancement, app, website, frontend

#35 Migrated to app router structure
  .babelrc
  app/globals.scss
  app/layout.tsx
  app/page.module.scss
  app/page.tsx
  public/favicon.ico
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/hello.ts
  src/pages/index.tsx
  tsconfig.json
Labels: documentation

#56 Implemented global loading component
  app/layout.tsx
  app/loading.module.scss
  app/loading.tsx
Labels: frontend

#57 created components directory for module and reusable components
  components/module-components/.placeholder
  components/reusable-components/.placeholder
Labels: frontend

#79 setup routing
  app/admin-dashboard/page.tsx
  app/blog/[slug]/page.tsx
  app/blog/page.tsx
  app/login/page.tsx
  app/member-dashboard/page.tsx
  app/signup/page.tsx
Labels: frontend

#81 implemented global styles with sass
  app/globals.scss
  app/layout.tsx
  app/page.tsx
  app/styles/globals/_boilerplate.scss
  app/styles/globals/_colors.scss
  app/styles/globals/_index.scss
  app/styles/globals/_typography.scss
  app/styles/main.scss
Labels: frontend

#86 Implemented global error and 404 page
  app/global-error.tsx
  app/not-found.tsx
Labels: frontend

#93 Set ESLint to use arrow function components
  .eslintrc.json
  app/layout.tsx
  app/loading.tsx
  app/page.tsx
Labels: frontend

#94 Convert the defined function declarations to arrow function components
  app/global-error.tsx
  app/not-found.tsx
  components/module-components/Hero/Hero.tsx
Labels: frontend

#92 Blog section #75
  app/page.tsx
  app/styles/globals/_boilerplate.scss
  app/styles/globals/_colors.scss
  components/module-components/BlogList/BlogList.tsx
  components/module-components/BlogList/blogList.module.scss
  components/reusable-components/BlogCard/BlogCard.tsx
  components/reusable-components/BlogCard/blogCard.module.scss
  package-lock.json
  package.json
Labels: enhancement, frontend

#98 created shorten string function and changed style for blog button
  components/module-components/BlogList/blogList.module.scss
  components/reusable-components/BlogCard/BlogCard.tsx
  components/reusable-components/BlogCard/blogCard.module.scss
  utils/shortenString.ts
Labels: enhancement, frontend

#99 created nested layout
  app/blog/layout.module.scss
  app/blog/layout.tsx
  components/module-components/.placeholder
  components/module-components/BlogList/BlogList.tsx
  components/reusable-components/.placeholder
  components/reusable-components/BlogCard/BlogCard.tsx
  components/reusable-components/Input/input.module.scss
  components/reusable-components/Input/input.tsx
Labels: enhancement, frontend

#111 fixed blogs fetch fail bug
  components/module-components/blog-list/BlogList.tsx
Labels: enhancement, frontend

#113 installed sharp package for image optimization
  package-lock.json
  package.json
Labels: enhancement, frontend

#109 #104 - created reusable blogs card
  app/blog/layout.module.scss
  app/blog/page.module.scss
  app/blog/page.tsx
  app/page.tsx
  app/styles/globals/_boilerplate.scss
  components/module-components/blog-list/BlogList.tsx
  components/module-components/blog-list/blogList.module.scss
  components/reusable-components/blog-card/BlogCard.tsx
  components/reusable-components/blog-card/blogCard.module.scss
  components/reusable-components/tab/Tab.tsx
  components/reusable-components/tab/tab.module.scss
Labels: enhancement, frontend

#124 #119 - fixed nested layout for blogs page
  app/blog/layout.module.scss
  app/blog/page.module.scss
  components/module-components/blog-list/blogList.module.scss
  components/reusable-components/input/input.module.scss
  components/reusable-components/tab/tab.module.scss
Labels: enhancement, frontend
